//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaRecurso
    {
        public int Id { get; set; }
        public Nullable<int> IdTarea { get; set; }
        public Nullable<int> IdRecurso { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<float> CostoTotal { get; set; }
    }
}
